/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-background': "#dae2fd",
        'inverse-primary': "#006c49",
        'on-secondary-fixed': "#0d1c2f",
        'on-error-container': "#ffdad6",
        'on-tertiary-container': "#00384e",
        'on-primary': "#003824",
        'tertiary': "#7bd0ff",
        'surface-container-high': "#222a3d",
        'surface-container-lowest': "#060e20",
        'error': "#ffb4ab",
        'primary-container': "#00b17b",
        'error-container': "#93000a",
        'background': "#0b1326",
        'tertiary-fixed': "#c4e7ff",
        'on-tertiary-fixed': "#001e2c",
        'primary': "#4edea3",
        'primary-fixed': "#6ffbbe",
        'surface-bright': "#31394d",
        'outline-variant': "#3e4850",
        'secondary-fixed-dim': "#b9c7e0",
        'primary-fixed-dim': "#4edea3",
        'on-surface-variant': "#bec8d2",
        'on-surface': "#dae2fd",
        'on-tertiary-fixed-variant': "#004c69",
        'on-primary-fixed-variant': "#005236",
        'secondary-container': "#3c4a5e",
        'surface-container-highest': "#2d3449",
        'surface-variant': "#2d3449",
        'surface-tint': "#4edea3",
        'on-error': "#690005",
        'tertiary-container': "#00a7e0",
        'surface-container-low': "#131b2e",
        'secondary': "#b9c7e0",
        'on-secondary-fixed-variant': "#3a485c",
        'on-primary-container': "#003b26",
        'surface-container': "#171f33",
        'inverse-on-surface': "#283044",
        'on-secondary-container': "#abb9d2",
        'on-secondary': "#233144",
        'tertiary-fixed-dim': "#7bd0ff",
        'outline': "#88929b",
        'on-primary-fixed': "#002113",
        'secondary-fixed': "#d5e3fd",
        'surface-dim': "#0b1326",
        'inverse-surface': "#dae2fd",
        'on-tertiary': "#00354a",
        'surface': "#0b1326"
      },
      fontFamily: {
        'headline': ['Space Grotesk'],
        'body': ['Inter'],
        'label': ['Manrope']
      },
      borderRadius: {
        'DEFAULT': "0.125rem",
        'lg': "0.25rem",
        'xl': "0.5rem",
        'full': "0.75rem"
      },
    },
  },
  plugins: [],
}